collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.727645
  lightness: 1
  brandColors:
    - '#FBFFFF'
    - '#0E0E0E'
    - '#4C4E37'
    - '#A5B1B1'
    - '#C8D4D4'
  rhythmicContrast: 1
layout_spectrum: 1
name: Dbthorn
